<?php
$parameters = array(
	'db_driver' => 'mysqli',
	'db_host' => 'localhost',
	'db_table_prefix' => null,
	'db_port' => '3306',
	'db_name' => 'updated_mautic',
	'db_user' => 'root',
	'db_password' => null,
	'db_backup_tables' => 1,
	'db_backup_prefix' => 'bak_',
	'db_server_version' => '5.5.5',
	'mailer_from_name' => 'Prabal Gupta',
	'mailer_from_email' => 'prabal1.gupta@gmail.com',
	'mailer_transport' => 'mail',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => null,
	'mailer_password' => null,
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/spool',
	'secret_key' => 'b30a01d2bd0f03c247116411c5e9aaf3aaf2d68d665cb5ef5615b8492fecc37a',
	'site_url' => 'http://test.updated-mautic.com',
);
